language: go

before_install:
- openssl aes-256-cbc -d
  -K $encrypted_9ca81b5594f5_key
  -iv $encrypted_9ca81b5594f5_iv
  -in $TRAVIS_BUILD_DIR/travis/mlab-sandbox-service-account.json.enc
  -out /tmp/sandbox-account.json
- openssl aes-256-cbc -d
  -K $encrypted_9ca81b5594f5_key
  -iv $encrypted_9ca81b5594f5_iv
  -in $TRAVIS_BUILD_DIR/travis/mlab-staging-service-account.json.enc
  -out /tmp/staging-account.json


cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script:
- go test -v ./...
- cd $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server && go build && ls
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh

# NB: travis has a "gae" provider, however it does not work here (unknown).
# Deploy steps never trigger on a new Pull Request. Deploy steps will trigger
# after a merge with matching "on:" conditions.
deploy:
  # TODO(soltesz): complete a production AppEngine deployment target.
  # PRODUCTION: after code review and after QA tests on staging have passed.
  - provider: script
    script: /bin/true
    skip_cleanup: true
    on:
      repo: m-lab/epoxy
      branch: master

  # STAGING: after code review and before QA testing.
  - provider: script
    script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging
      /tmp/staging-account.json $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server
    skip_cleanup: true
    on:
      repo: m-lab/epoxy
      branch: dev

  # SANDBOX: before code review for development code in a specific branch.
  - provider: script
    script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-sandbox
      /tmp/sandbox-account.json $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server
    skip_cleanup: true
    on:
      branch: sandbox
