language: go

before_install:
# Encrypted values are not defined in forks or pull requests.
- if [[ -n "$encrypted_2ac64e4220d5_iv" ]] ; then
    openssl aes-256-cbc -d
      -K $encrypted_2ac64e4220d5_key
      -iv $encrypted_2ac64e4220d5_iv
      -in $TRAVIS_BUILD_DIR/travis/service-accounts.tar.enc
      -out /tmp/service-accounts.tar ;
    tar -C /tmp -xvf /tmp/service-accounts.tar ;
  fi

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script:
- go test -v ./...
- cd $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server && go build
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh

# NB: travis has a "gae" provider, however it does not work here (unknown).
# Deploy steps never trigger on a new Pull Request. Deploy steps will trigger
# after a merge with matching "on:" conditions.
deploy:
  # TODO(soltesz): complete a production AppEngine deployment target.
  # PRODUCTION: after code review and after QA tests on staging have passed.
  - provider: script
    script: /bin/true
    skip_cleanup: true
    on:
      repo: m-lab/epoxy
      branch: master

  # STAGING: after code review and before QA testing.
  - provider: script
    script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging
      /tmp/mlab-staging-service-account.json
      $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server
    skip_cleanup: true
    on:
      repo: m-lab/epoxy
      branch: dev

  # SANDBOX: before code review for development code in a specific branch.
  - provider: script
    script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-sandbox
      /tmp/mlab-sandbox-service-account.json
      $TRAVIS_BUILD_DIR/cmd/epoxy_boot_server
    skip_cleanup: true
    on:
      # Consider all branches and match using the condition. By default
      # "all_branches" is false, and the condition is ignored.
      all_branches: true
      # A bash-style 'if' condition, matching branches with a "sandbox-" prefix.
      condition: $TRAVIS_BRANCH == sandbox-*
