language: go
before_install:
- openssl aes-256-cbc -K $encrypted_9ca81b5594f5_key -iv $encrypted_9ca81b5594f5_iv
  -in .mlab-sandbox-appengine-deploy.json.enc -out /tmp/mlab-sandbox-appengine-deploy.json
  -d

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# install:
# - go get -t ./...
#   # - go get google.golang.org/appengine/cmd/aedeploy

script:
- go test -v ./...
- cd cmd/epoxy_boot_server && go build && ls
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version

deploy:
  provider: script
  script: $TRAVIS_BUILD_DIR/deploy.sh
  skip_cleanup: true

#deploy:
#  verbosity: debug
#  config: cmd/epoxy_boot_server/app.yaml
#  provider: gae
#  keyfile: /tmp/mlab-sandbox-appengine-deploy.json
#  project: mlab-sandbox
