# Timeout for complete build. Default is 10m.
timeout: 1800s

steps:
# Create the image for later steps.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'gcr.io/$PROJECT_ID/epoxy_boot_server:$BUILD_ID', '.'
  ]
# Make the new container available immediately.
- name: gcr.io/cloud-builders/docker
  args: [
    'push', 'gcr.io/$PROJECT_ID/epoxy_boot_server:$BUILD_ID'
  ]
# Deploy to GCE.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
   - '/workspace/deploy_epoxy_container.sh'
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'CONTAINER=gcr.io/$PROJECT_ID/epoxy_boot_server:$BUILD_ID'
   # NOTE: Changing zones will require manual intervention.
   - 'ZONE_mlab_sandbox=us-west2-c'
   - 'ZONE_mlab_staging=us-central1-b'
   - 'ZONE_mlab_oti=us-east1-c'

